In [435]:
import numpy as np
import hashlib

Name A: Nick Askari 

Name B: Simen Peder Stang

In [436]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
Sentence_4 = "The project data for students are on Blackboard not Piazza"

In [437]:
# Enter the unique words list here, alphabetically sorted
unique_words = ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']

In [438]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(input("Enter your created list of unique words: ")) 

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma
Correct! Your dictionary matched!


In [439]:
# Create an empty array of input matrix
Input_Matrix = np.zeros((len(unique_words), 4), dtype=int)

In [440]:
Sentence_1, Sentence_2, Sentence_3, Sentence_4 = [sentence.lower()
                                                  for sentence in [Sentence_1, Sentence_2, Sentence_3, Sentence_4]]

print('1: ', Sentence_1, '\n2: ', Sentence_2, '\n3: ', Sentence_3, '\n4: ', Sentence_4)

1:  the big data platform for students is blackboard 
2:  questions on minhash project by ntnu students is on piazza 
3:  ntnu big data platform are blackboard and piazza 
4:  the project data for students are on blackboard not piazza


In [441]:
## Compute the values for the input matrix here ##

sentences = [Sentence_1, Sentence_2, Sentence_3, Sentence_4]
for i, word in enumerate(unique_words):
    for j, sentence in enumerate(sentences):
        if word in sentence:
            Input_Matrix[i, j] = 1

Input_Matrix

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 1]])

In [442]:
# Create a MinHash signature matrix array with inf values
Sig_M = np.full((3, 4), np.inf)
Sig_M

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [443]:
# Generate hash functions
import random
n = len(unique_words)
x = random.randint(1, 100)

In [444]:
#hash_1 = random.sample(range(1, n + 1), n)

hash_1 = []
for i in range(1, n + 1):
    hash_1.append( ( ( (i + 3) % 10 ) + 1) )

In [445]:
#hash_2 = random.sample(range(1, n + 1), n)

hash_2 = []
for i in range(1, n + 1):
    hash_2.append( ( ( (7 * i + 1) % 10 ) + 1) )

In [446]:
#hash_3 = random.sample(range(1, n + 1), n)

hash_3 = []
for i in range(1, n + 1):
    hash_3.append( ( ( (7 * i + 2) % 10 ) + 1) )

In [447]:
hash_list = [hash_1, hash_2, hash_3]

In [448]:
hash_list

[[5, 6, 7, 8, 9, 10, 1, 2, 3, 4],
 [9, 6, 3, 10, 7, 4, 1, 8, 5, 2],
 [10, 7, 4, 1, 8, 5, 2, 9, 6, 3]]

In [449]:
## Using the hash functions and the input matrix compute the MinHash signature matrix here ##

for i in range(Sig_M.shape[0]):
    for j in range(Sig_M.shape[1]):
        for k in range(len(unique_words)):
            if Input_Matrix[k, j] == 1:
                Sig_M[i, j] = min(Sig_M[i, j], hash_list[i][k])


In [450]:
# print the updated MinHash signature matrix

Sig_M = Sig_M.astype(int)
Sig_M

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [2, 1, 2, 3]])

In [451]:
def jaccard_similarity(Sig_M, i, j):
    return np.sum(Sig_M[:, i] == Sig_M[:, j]) / Sig_M.shape[0]

for i in range(Sig_M.shape[1]):
    for j in range(i + 1, Sig_M.shape[1]):
        print(f"Jaccard Similarity between Sentence {i + 1} and Sentence {j + 1} is {jaccard_similarity(Sig_M, i, j)}")

Jaccard Similarity between Sentence 1 and Sentence 2 is 0.0
Jaccard Similarity between Sentence 1 and Sentence 3 is 1.0
Jaccard Similarity between Sentence 1 and Sentence 4 is 0.0
Jaccard Similarity between Sentence 2 and Sentence 3 is 0.0
Jaccard Similarity between Sentence 2 and Sentence 4 is 0.6666666666666666
Jaccard Similarity between Sentence 3 and Sentence 4 is 0.0
