In [570]:
import numpy as np
import hashlib

Name A: Nick Askari 

Name B: Simen Peder Stang

In [571]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
Sentence_4 = "The project data for students are on Blackboard not Piazza"

In [572]:
# Enter the unique words list here, alphabetically sorted
unique_words = ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']

In [573]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(input("Enter your created list of unique words: ")) 

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma
Incorrect! Try again.


In [574]:
# Create an empty array of input matrix
Input_Matrix = np.zeros((len(unique_words), 4), dtype=int)

In [575]:
## Compute the values for the input matrix here ##
#NB: gets different order from overleaf due to alphabetical oredring of words

Sentence_1, Sentence_2, Sentence_3, Sentence_4 = [sentence.lower()
                                                   for sentence in [Sentence_1, Sentence_2, Sentence_3, Sentence_4]]

sentences = [Sentence_1, Sentence_2, Sentence_3, Sentence_4]
for i, word in enumerate(unique_words):
    for j, sentence in enumerate(sentences):
        if word in sentence:
            Input_Matrix[i, j] = 1

Input_Matrix

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 1]])

In [576]:
# Create a MinHash signature matrix array with inf values
Sig_M = np.full((3, 4), np.inf)
Sig_M

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [577]:
# Generate hash functions
import random
n = len(unique_words)

In [578]:
hash_1 = random.sample(range(1, n + 1), n)

In [579]:
hash_2 = random.sample(range(1, n + 1), n)

In [580]:
hash_3 = random.sample(range(1, n + 1), n)

In [581]:
hash_list = [hash_1, hash_2, hash_3]

In [582]:
hash_list

[[4, 2, 10, 8, 9, 6, 5, 7, 1, 3],
 [5, 9, 6, 1, 7, 10, 3, 2, 8, 4],
 [3, 10, 9, 5, 6, 8, 4, 1, 7, 2]]

In [583]:
## Using the hash functions and the input matrix compute the MinHash signature matrix here ##

for i in range(Sig_M.shape[0]):
    for j in range(Sig_M.shape[1]):
        for k in range(len(unique_words)):
            if Input_Matrix[k, j] == 1:
                Sig_M[i, j] = min(Sig_M[i, j], hash_list[i][k])


In [584]:
# print the updated MinHash signature matrix

Sig_M = Sig_M.astype(int)
Sig_M

array([[2, 1, 2, 2],
       [3, 1, 3, 2],
       [2, 1, 3, 1]])