In [375]:
import numpy as np
import hashlib

Name A: Nick Askari 

Name B: Simen Peder Stang

In [376]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
Sentence_4 = "The project data for students are on Blackboard not Piazza"

In [377]:
# Enter the unique words list here, alphabetically sorted
unique_words = ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']

In [378]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(input("Enter your created list of unique words: ")) 

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma
Incorrect! Try again.


In [379]:
# Create an empty array of input matrix
Input_Matrix = np.zeros((len(unique_words), 4), dtype=int)

In [380]:
Sentence_1, Sentence_2, Sentence_3, Sentence_4 = [sentence.lower()
                                                  for sentence in [Sentence_1, Sentence_2, Sentence_3, Sentence_4]]

print('1: ', Sentence_1, '\n2: ', Sentence_2, '\n3: ', Sentence_3, '\n4: ', Sentence_4)

1:  the big data platform for students is blackboard 
2:  questions on minhash project by ntnu students is on piazza 
3:  ntnu big data platform are blackboard and piazza 
4:  the project data for students are on blackboard not piazza


In [381]:
## Compute the values for the input matrix here ##

sentences = [Sentence_1, Sentence_2, Sentence_3, Sentence_4]
for i, word in enumerate(unique_words):
    for j, sentence in enumerate(sentences):
        if word in sentence:
            Input_Matrix[i, j] = 1

Input_Matrix

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 1]])

In [382]:
# Create a MinHash signature matrix array with inf values
Sig_M = np.full((3, 4), np.inf)
Sig_M

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [383]:
# Generate hash functions
import random
n = len(unique_words)
x = random.randint(1, 100)

In [384]:
#hash_1 = random.sample(range(1, n + 1), n)

hash_1 = []
for i in range(1, n + 1):
    hash_1.append( ( ( (i + 3) % 10 ) + 1) )

In [385]:
#hash_2 = random.sample(range(1, n + 1), n)

hash_2 = []
for i in range(1, n + 1):
    hash_2.append( ( ( (7 * i + 1) % 10 ) + 1) )

In [386]:
#hash_3 = random.sample(range(1, n + 1), n)

hash_3 = []
for i in range(1, n + 1):
    hash_3.append( ( ( (7 * i + 2) % 10 ) + 1) )

In [387]:
hash_list = [hash_1, hash_2, hash_3]

In [388]:
hash_list

[[5, 6, 7, 8, 9, 10, 1, 2, 3, 4],
 [9, 6, 3, 10, 7, 4, 1, 8, 5, 2],
 [10, 7, 4, 1, 8, 5, 2, 9, 6, 3]]

In [389]:
# for usage in part one
'''
hash_list = [
    [5, 6, 7, 8, 9, 10, 1, 2, 3, 4],
    [9, 6, 3, 10, 7, 4, 1, 8, 5, 2],
    [10, 7, 4, 1, 8, 5, 2, 9, 6, 3]
    ]
'''

'\nhash_list = [\n    [5, 6, 7, 8, 9, 10, 1, 2, 3, 4],\n    [9, 6, 3, 10, 7, 4, 1, 8, 5, 2],\n    [10, 7, 4, 1, 8, 5, 2, 9, 6, 3]\n    ]\n'

In [390]:
## Using the hash functions and the input matrix compute the MinHash signature matrix here ##

for i in range(Sig_M.shape[0]):
    for j in range(Sig_M.shape[1]):
        for k in range(len(unique_words)):
            if Input_Matrix[k, j] == 1:
                Sig_M[i, j] = min(Sig_M[i, j], hash_list[i][k])


In [391]:
# print the updated MinHash signature matrix

Sig_M = Sig_M.astype(int)
Sig_M

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [2, 1, 2, 3]])

In [392]:
def jaccard_similarity(Sig_M, i, j):
    return np.sum(Sig_M[:, i] == Sig_M[:, j]) / Sig_M.shape[0]

for i in range(Sig_M.shape[1]):
    for j in range(i + 1, Sig_M.shape[1]):
        print(f"Jaccard Similarity between Sentence {i + 1} and Sentence {j + 1} is {jaccard_similarity(Sig_M, i, j)}")

Jaccard Similarity between Sentence 1 and Sentence 2 is 0.0
Jaccard Similarity between Sentence 1 and Sentence 3 is 1.0
Jaccard Similarity between Sentence 1 and Sentence 4 is 0.0
Jaccard Similarity between Sentence 2 and Sentence 3 is 0.0
Jaccard Similarity between Sentence 2 and Sentence 4 is 0.6666666666666666
Jaccard Similarity between Sentence 3 and Sentence 4 is 0.0


In [393]:
import random


def next_prime(N):
    def is_prime(n):
        if n <= 2:
            return n == 2
        if n % 2 == 0:
            return False
        p = 3
        while p * p <= n:
            if n % p == 0:
                return False
            p += 2
        return True

    prime = N + 1
    while not is_prime(prime):
        prime += 1
    return prime

In [394]:
next_prime(len(unique_words))

11

In [395]:
# problem with uniqueness 

def generate_hash_functions(num_perm, N):
    p = next_prime(N)
    hash_funcs = []

    for i in range(num_perm):
        a = random.randint(1, p - 1)
        b = random.randint(0, p - 1)
        hash_list = [ ((a * x + b) % (p - 1) + 1 ) for x in range(1, N + 1)]
        hash_funcs.append(hash_list)

    return hash_funcs

In [396]:
funcs = generate_hash_functions(10, len(unique_words))
funcs

[[4, 5, 6, 7, 8, 9, 10, 1, 2, 3],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [8, 3, 8, 3, 8, 3, 8, 3, 8, 3],
 [2, 8, 4, 10, 6, 2, 8, 4, 10, 6],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 1],
 [10, 5, 10, 5, 10, 5, 10, 5, 10, 5],
 [6, 10, 4, 8, 2, 6, 10, 4, 8, 2],
 [5, 2, 9, 6, 3, 10, 7, 4, 1, 8],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 1],
 [9, 4, 9, 4, 9, 4, 9, 4, 9, 4]]

In [397]:
# possible solution to the uniqueness problem, just a shuffle

def generate_permutations(num_perm, N):
    permutations = []

    for _ in range(num_perm):
        perm = list(range(1, N + 1))
        random.shuffle(perm)  # Shuffle the list in-place
        permutations.append(perm)

    return permutations

In [398]:
generate_permutations(10, len(unique_words))


[[10, 7, 1, 3, 9, 5, 8, 2, 6, 4],
 [2, 8, 9, 1, 7, 5, 4, 3, 10, 6],
 [9, 5, 8, 2, 6, 7, 4, 1, 3, 10],
 [4, 5, 6, 9, 3, 7, 8, 1, 10, 2],
 [7, 3, 6, 9, 5, 1, 4, 10, 8, 2],
 [2, 4, 3, 5, 9, 8, 7, 6, 1, 10],
 [9, 10, 8, 5, 1, 3, 4, 2, 7, 6],
 [6, 2, 1, 5, 7, 10, 4, 9, 8, 3],
 [6, 8, 3, 2, 1, 4, 9, 10, 7, 5],
 [4, 5, 10, 3, 6, 2, 9, 8, 7, 1]]

In [403]:
def minHash(docs_signature_sets, hash_fn):
    min_hash_signatures = []

    # columns, number of txt files. Rows are shingles
    num_docs = docs_signature_sets.shape[1]
    num_permutation = len(hash_fn)
    min_hash_signatures = np.full((num_permutation, num_docs), np.inf)

    for perm_idx, hash_list in enumerate(hash_fn):
        #print('IM HERE 1: ', perm_idx)
        for doc_idx in range(num_docs):
            for shingle_idx in range(docs_signature_sets.shape[0]):
                if docs_signature_sets[shingle_idx, doc_idx] == 1:
                    #print('IM HERE 4: ', doc_idx, ', ', shingle_idx)
                    min_hash_signatures[perm_idx, doc_idx] = min(
                        min_hash_signatures[perm_idx, doc_idx], hash_list[shingle_idx])

    return min_hash_signatures

In [405]:
docs_signature_sets = Input_Matrix
hash_fn = hash_list

hashen = minHash(docs_signature_sets, hash_fn)
hashen

array([[1., 2., 1., 2.],
       [1., 2., 1., 2.],
       [2., 1., 2., 3.]])